### ISSUE TITLE
Corresponding Paper

### ISSUE THREAD

**Issue by patripfr** [Liansheng-Wang/InGM-LIO#1]
Hi,
your work sounds very interesting! Is the preprint of the paper available?

**Comment by Liansheng-Wang** [comment]
I’m currently waiting for the review of the paper, and once the results are available, I will release the code and the paper immediately. Thank you so much for your attention! I’ve previously seen your COIN-LIO work, and it's an outstanding contribution!

**Comment by Liansheng-Wang** [comment]
> Hi, your work sounds very interesting! Is the preprint of the paper available?

I’m currently waiting for the review of the paper, and once the results are available, I will release the code and the paper immediately. Thank you so much for your attention! I’ve previously seen your COIN-LIO work, and it's an outstanding contribution!

**Comment by patripfr** [comment]
It would be very cool if you could share it already earlier. It's usually good practice to upload the paper already after submission to avoid redundancy with other researchers working on the same idea in the meantime, since it takes a long time (especially for ICRA) until reviews are available. Is there a particular reason why you can't share it earlier? 
Thanks for the nice words about COIN-LIO :)

**Comment by Liansheng-Wang** [comment]
> It would be very cool if you could share it already earlier. It's usually good practice to upload the paper already after submission to avoid redundancy with other researchers working on the same idea in the meantime, since it takes a long time (especially for ICRA) until reviews are available. Is there a particular reason why you can't share it earlier? Thanks for the nice words about COIN-LIO :)

Your suggestion makes a lot of sense. We originally planned to open-source the project after the paper was accepted, but we will take your suggestion into consideration. Once the related video files are submitted, we will re-evaluate the process and discuss whether to adjust the timeline for open-sourcing. Thank you again for your attention!
